### ISSUE TITLE
EN list with descriptions is needed too

### ISSUE THREAD

**Issue by CudaText-addons** [CudaText-addons/cuda_insert_emoji#2]
@ildarkhasanshin Can you pls add
https://www.emojiall.com/en/all-emojis
too?

I suggest to make ONE root menuitem in Plugins with 3 sub items

- Insert code from picture list
- Insert unicode (En descriptions)
- Insert unicode (Ru descriptions)

**Comment by ildarkhasanshin** [comment]
https://github.com/CudaText-addons/cuda_insert_emoji/pull/3

**Comment by Alexey-T** [comment]
@ildarkhasanshin sync your fork, pls. i made fixes.
