### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by eltonfabricio10** [CudaText-addons/cuda_insert_emoji#4]
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by Alexey-T** [comment]
What data in plugin we need to update - set of icons? Set of text abbreviations ?

**Comment by eltonfabricio10** [comment]
Icons and text

**Comment by Alexey-T** [comment]
Maybe patch is welcome ..

**Comment by eltonfabricio10** [comment]
I saw that what's in the plugin is enough.

**Comment by ildarkhasanshin** [comment]
@eltonfabricio10, db updated
